app = "safety-straw"

[[services]]
  internal_port = 5000
  protocol = "tcp"
  [[services.ports]]
    handlers = ["http"]
    port = 80
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
  [build.args]
  REACT_APP_BASE_URL = "https://safety-straw.fly.dev/"
  VITE_BASE_URL = "https://safety-straw.fly.dev/"